const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidStyles, withDangerousMod } = require('expo/config-plugins');

/**
 * Shows the full-screen HerdCare artwork at launch on Android, instead of a small icon.
 *
 * Why this exists: expo-splash-screen can only place an icon in the centre of a flat colour, because
 * that is all Android's launch screen supports. So the artwork is installed as the *window
 * background* instead, which Android paints natively the moment the app starts — before any
 * JavaScript runs, so there is no wait and no blank frame.
 *
 * What a farmer sees:
 *   Android 11 and older   The artwork, and nothing else, from the first frame.
 *   Android 12 and newer   The operating system paints one frame of solid colour first (it does this
 *                          for every app and no app can remove it), then the artwork, then HerdCare.
 *
 * Why it is three layers and not one image: phones are taller than the 9:16 artwork, and Android
 * cannot crop a bitmap to cover the screen, only stretch it, which would squash the logo. So the
 * background stretches to fill — invisible on wavy contour lines — while the logo and tagline keep
 * their true proportions at a fixed size. Layer geometry is measured from assets/splash.png.
 */

const LAYERS_DIR = 'assets/splash-layers';

/** Measured from the 1080x1920 artwork, which is a 360dp-wide screen at xxhdpi. */
const GEOMETRY = {
  lockup: { widthDp: 245.3, heightDp: 232.0, liftDp: 17.7 },
  tagline: { widthDp: 240.7, heightDp: 22.3, bottomDp: 32.7 },
};

const DRAWABLE_NAME = 'splash_fullscreen';

function layerListXml() {
  const { lockup, tagline } = GEOMETRY;
  // `android:bottom` on a centred item shrinks its bounds from below, lifting its centre by half —
  // which is how the logo keeps the same slight rise above centre that it has in the artwork.
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withFullscreenSplash.js. Do not edit; change the plugin instead. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
  <item android:drawable="@drawable/splash_bg" />
  <item
    android:gravity="center"
    android:width="${lockup.widthDp}dp"
    android:height="${lockup.heightDp}dp"
    android:bottom="${(lockup.liftDp * 2).toFixed(1)}dp"
    android:drawable="@drawable/splash_lockup" />
  <item
    android:gravity="bottom|center_horizontal"
    android:width="${tagline.widthDp}dp"
    android:height="${tagline.heightDp}dp"
    android:bottom="${tagline.bottomDp}dp"
    android:drawable="@drawable/splash_tagline" />
</layer-list>
`;
}

function withSplashDrawables(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const res = path.join(modConfig.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');

      // nodpi: these are sized in dp by the layer-list, so Android must not rescale them per density.
      const nodpi = path.join(res, 'drawable-nodpi');
      const drawable = path.join(res, 'drawable');
      fs.mkdirSync(nodpi, { recursive: true });
      fs.mkdirSync(drawable, { recursive: true });

      const copies = [
        ['background.jpg', 'splash_bg.jpg'],
        ['lockup.png', 'splash_lockup.png'],
        ['tagline.png', 'splash_tagline.png'],
      ];
      for (const [from, to] of copies) {
        const source = path.join(projectRoot, LAYERS_DIR, from);
        if (!fs.existsSync(source)) {
          throw new Error(`withFullscreenSplash: missing ${path.join(LAYERS_DIR, from)}`);
        }
        fs.copyFileSync(source, path.join(nodpi, to));
      }

      fs.writeFileSync(path.join(drawable, `${DRAWABLE_NAME}.xml`), layerListXml());
      return modConfig;
    },
  ]);
}

function withSplashWindowBackground(config) {
  return withAndroidStyles(config, (modConfig) => {
    const value = `@drawable/${DRAWABLE_NAME}`;

    // The launch theme: this is what Android 11 and older paint at cold start.
    modConfig.modResults = AndroidConfig.Styles.assignStylesValue(modConfig.modResults, {
      add: true,
      name: 'android:windowBackground',
      value,
      parent: { name: 'Theme.App.SplashScreen' },
    });

    // The app theme: what shows once Android 12+'s own launch frame lifts, until HerdCare draws.
    // Matched by name only, since its parent changes with edge-to-edge settings.
    modConfig.modResults = AndroidConfig.Styles.assignStylesValue(modConfig.modResults, {
      add: true,
      name: 'android:windowBackground',
      value,
      parent: AndroidConfig.Styles.getAppThemeGroup(),
    });

    return modConfig;
  });
}

module.exports = function withFullscreenSplash(config) {
  return withSplashWindowBackground(withSplashDrawables(config));
};
